name: Node.js CI

on:
  push:
    branches: [ "main", "feat/fmano" ]
  pull_request:
    branches: [ "main" ]

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      # Install dependencies for the frontend
      - name: Install frontend dependencies
        working-directory: frontend/altar-spa
        run: npm install
      
      # Install dependencies for the backend
      - name: Install backend dependencies
        working-directory: backend/altar-app
        run: npm install

  build:
    runs-on: ubuntu-latest
    needs: install

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Angular CLI globally
        run: npm install -g @angular/cli

      # Build the frontend using Angular CLI
      - name: Build Frontend
        working-directory: frontend/altar-spa
        run: npm run build

      # Build the backend
      - name: Build Backend
        working-directory: backend/altar-app
        run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - uses: actions/checkout@v4
      
      # Run frontend tests
      - name: Install frontend dependencies
        working-directory: frontend/altar-spa
        run: npm test
      
      # Run backend tests
      - name: Install backend dependencies
        working-directory: backend/altar-app
        run: npm test
